# Generated by Django 3.0.3 on 2020-04-06 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matcher', '0005_penaltygroup_custom_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_user_id', models.CharField(max_length=20)),
                ('roulette_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matcher.RouletteUser')),
            ],
        ),
    ]
