# Generated by Django 3.0.3 on 2020-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0005_slackroulette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackadminuser',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='slackuser',
            name='slack_user_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
