# Generated by Django 3.0.3 on 2020-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0006_auto_20200511_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackroulette',
            name='channel_id',
            field=models.CharField(default='dummy-channel-name', max_length=20),
            preserve_default=False,
        ),
    ]
