# Generated by Django 3.0.3 on 2020-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0007_slackroulette_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackadminuser',
            name='slack_user_id',
            field=models.CharField(default='non-existent-id', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
