# Generated by Django 3.0.3 on 2020-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slackbot', '0008_auto_20200512_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWorkspace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roulette_channel', models.CharField(help_text='Name of the Slack channel that the bot will post public messages on. Starts with #.', max_length=255)),
                ('bot_api_token', models.CharField(help_text='A secret token that allows using Slack Web API, tied to a Slack app installation.', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
