# Generated by Django 3.0.2 on 2020-01-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyForNumberOfMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.FloatField(default=0.5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenaltyForPenaltyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.FloatField(default=2.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PenaltyForRecentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.FloatField(default=1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_deadline', models.DateTimeField()),
                ('coffee_deadline', models.DateTimeField()),
                ('matching_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouletteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('0', 'No vote')], default='0', max_length=3)),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.Roulette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.RouletteUser')),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(to='matcher.RouletteUser')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.Roulette')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matcher.RouletteUser')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='matcher.RouletteUser')),
            ],
        ),
        migrations.CreateModel(
            name='ExclusionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ManyToManyField(to='matcher.RouletteUser')),
            ],
        ),
    ]
