# Generated by Django 3.0.2 on 2020-01-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roulette',
            old_name='matching_date',
            new_name='matchings_found_on',
        ),
    ]
