# Generated by Django 3.0.2 on 2020-02-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20200126_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyForGroupingWithForbiddenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty', models.FloatField(default=10.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
