# Generated by Django 3.0.2 on 2020-02-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0003_penaltyforgroupingwithforbiddenuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exclusiongroup',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='penaltygroup',
            old_name='user',
            new_name='users',
        ),
        migrations.AddField(
            model_name='exclusiongroup',
            name='custom_name',
            field=models.CharField(blank=True, help_text='If left empty, it will be automatically generated.', max_length=128),
        ),
    ]
