# Generated by Django 3.0.2 on 2020-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_auto_20200215_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltygroup',
            name='custom_name',
            field=models.CharField(blank=True, help_text='If left empty, it will be automatically generated.', max_length=128),
        ),
    ]
