# Generated by Django 3.0.3 on 2020-05-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0006_auto_20200511_1624'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('roulette', 'user'), name='unique_vote'),
        ),
    ]
